[package]
name = "malaphors"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
elementtree = "0.7.0"
reqwest = "0.11.9"
tokio = { version = "1", features = ["full"] }
